name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: yarn config set enableGlobalCache true
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: ./yarn.lock
    - run: yarn
    - run: yarn jest --coverage
    - uses: codecov/codecov-action@v3
